import { writeFileSync, existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { createLogger } from './logger.js'

const logger = createLogger('docker')

const COLORS = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
}

function readSettingsEnv(): Record<string, string> {
  try {
    const settingsPath = join(homedir(), '.claude', 'settings.json')
    const raw = readFileSync(settingsPath, 'utf-8')
    const parsed = JSON.parse(raw) as Record<string, unknown>
    return (parsed['env'] as Record<string, string>) ?? {}
  } catch {
    return {}
  }
}

export async function generateDockerCompose(): Promise<void> {
  const env = readSettingsEnv()
  const token = env['REX_TELEGRAM_BOT_TOKEN'] ?? ''
  const chatId = env['REX_TELEGRAM_CHAT_ID'] ?? ''
  const hubToken = env['REX_HUB_TOKEN'] ?? ''
  const ollamaUrl = env['OLLAMA_URL'] ?? 'http://ollama:11434'

  const cwd = process.cwd()
  const outPath = join(cwd, 'docker-compose.local.yml')
  const envPath = join(cwd, '.env.docker')

  if (existsSync(outPath)) {
    console.log(`${COLORS.yellow}⚠${COLORS.reset}  docker-compose.local.yml already exists — skipping (delete it to regenerate)`)
    return
  }

  const compose = `# REX local docker-compose — generated by rex init --docker
# Edit as needed. Start with: docker compose -f docker-compose.yml -f docker-compose.local.yml up -d

services:
  rex-hub:
    environment:
      OLLAMA_URL: ${ollamaUrl.replace('http://localhost:11434', 'http://ollama:11434')}
    volumes:
      - ${homedir()}/.claude/rex:/data
`

  const envFile = `# REX Docker environment variables
# Fill in any missing values before starting
REX_TELEGRAM_BOT_TOKEN=${token}
REX_TELEGRAM_CHAT_ID=${chatId}
REX_HUB_TOKEN=${hubToken || '<generate with: rex hub token>'}

# VPS only (docker-compose.vps.yml)
REX_DOMAIN=rex.yourdomain.com
ACME_EMAIL=you@yourdomain.com
`

  writeFileSync(outPath, compose, 'utf-8')
  writeFileSync(envPath, envFile, 'utf-8')

  logger.info('Docker compose files generated')

  console.log(`\n${COLORS.bold}${COLORS.green}✓ Docker deployment files generated${COLORS.reset}\n`)
  console.log(`  ${COLORS.cyan}docker-compose.local.yml${COLORS.reset}  — local overrides (your paths + env)`)
  console.log(`  ${COLORS.cyan}.env.docker${COLORS.reset}               — environment variables\n`)
  console.log(`${COLORS.bold}Next steps:${COLORS.reset}`)
  console.log(`  1. Edit ${COLORS.dim}.env.docker${COLORS.reset} with your credentials`)
  console.log(`  2. ${COLORS.dim}docker compose -f docker-compose.yml -f docker-compose.local.yml up -d${COLORS.reset}`)
  console.log(`  3. Pull Ollama models: ${COLORS.dim}docker exec rex-hub-ollama-1 ollama pull qwen2.5:7b${COLORS.reset}`)
  console.log(`\n  For VPS + HTTPS: add ${COLORS.dim}docker-compose.vps.yml${COLORS.reset} to the compose chain\n`)
}
